version: '3.8'
services:
  fe-app:
    image: fe-container-images:v1
    ports:
      - "80:80"
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
    # ports:
    #   - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /root/database
    environment:
      MYSQL_DATABASE: local_blog
      MYSQL_ROOT_PASSWORD: xqs
    ports:
      - 3306:3306
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
